[env]
_.python.venv = { path = ".venv", create = true }
_.path = ['{{config_root}}/node_modules/.bin']
NODE_PATH = '{{config_root}}/node_modules'

[tools]
prek = "latest"
uv = "latest"
python = "3.14"
node = "24"
"npm:semantic-release" = "25.0.3"
"npm:@semantic-release/changelog" = "6.0.3"
"npm:@semantic-release/git" = "10.0.1"
"npm:@semantic-release/commit-analyzer" = "11.1.0"
"npm:@semantic-release/release-notes-generator" = "12.1.0"
"npm:@semantic-release/github" = "9.2.1"

[tasks.deps]
run = "uv pip install -r requirements.txt"
