[env]
_.python.venv = { path = ".venv", create = true }
_.path = ['{{config_root}}/node_modules/.bin']

[tools]
prek = "latest"
uv = "latest"
python = "3.14"
node = "24"
"npm:semantic-release" = "25.0.3"
"npm:@semantic-release/changelog" = "6.0.3"
"npm:@semantic-release/git" = "10.0.1"

[tasks.deps]
run = "uv pip install -r requirements.txt"
