---
name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install python requirements
        run: pip3 install ansible[docker]
      - name: Apply locally
        run: ansible-playbook -c local -i localhost, ${PWD}/examples/three-node-cluster/playbook.yml
        env:
          ANSIBLE_ROLES_PATH: "${GITHUB_WORKSPACE}/../"
